# This file provides SonarQube-related settings.
# For available switches and their documentation, see
# https://sonar.contact.de/project/settings?id=cs.template%3Amaster

# Basic properties defining the identity, name, version ...
#
sonar.projectKey=csspin-tooling
sonar.projectName=csspin-tooling
sonar.sourceEncoding=UTF-8

# Allow to directly navigate to other interesting places from
# projects home page in Sonar
#
sonar.links.homepage=https://csspin-tooling.readthedocs.io/en/stable
sonar.links.issue=https://code.contact.de/pod/components/csspin-tooling/-/work_items
sonar.links.scm=https://code.contact.de/pod/components/csspin-tooling

# Define the scope by including or excluding directories/files
#
sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=**/test_*.py

# Sonar uses SCM history when analyzing the sources.
# Be sure to provide the proper URL
sonar.scm.url=scm:git:https://code.contact.de/pod/components/csspin-tooling.git

# Python-plugin-related settings
#
sonar.python.xunit.skipDetails=False
sonar.python.coverage.reportPaths=python*coverage*.xml
sonar.python.pylint.reportPaths=pylint-report.txt
sonar.python.xunit.reportPath=reports/*.xml

# Define the target Python version for the analysis.
#
sonar.python.version=3.10,3.11,3.12,3.13,3.14

# Wait for the background job, which runs async.
# Thus the coverage number is available and can be used for
# https://docs.gitlab.com/ee/ci/pipelines/settings.html#add-test-coverage-results-to-a-merge-request
sonar.qualitygate.wait=true
